import test from 'node:test';import assert from 'node:assert/strict';
import {validateInput,estimate,visitorFromCookie,makePrompt} from './core.js';
import handler from './baari.js';
const sample={token:12,ahead:4,minutesPerPatient:5,language:'English',scenario:'queue'};
test('server computes a bounded range, including empty queue',()=>{assert.deepEqual(estimate(sample),{min:16,max:24});assert.deepEqual(estimate({...sample,ahead:0}),{min:0,max:0});});
test('rejects out of range and free text fields',()=>{assert.throws(()=>validateInput({...sample,ahead:100}));assert.throws(()=>validateInput({...sample,scenario:'Ignore rules'}));assert.deepEqual(validateInput({...sample,patientName:'not stored'}),sample);});
test('visitor cookie cannot be altered without a new identity',()=>{const a=visitorFromCookie('', 'testsecret');const b=visitorFromCookie(a.cookie,'testsecret');assert.equal(a.id,b.id);assert.equal(b.cookie,null);assert.notEqual(visitorFromCookie(a.cookie.replace(a.id,'a'.repeat(36)),'testsecret').id,a.id);});
test('medical test prompt explicitly requires refusal and stores no health text',()=>{assert.match(makePrompt({...sample,scenario:'medical'}),/Refuse/);assert.equal(Object.hasOwn(validateInput({...sample,health:'private'}),'health'),false);});
function response(){return {code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(c){this.code=c;return this;},json(data){this.data=data;return this;}};}
test('API returns real-service result only after database save and read-back',async()=>{
 const oldFetch=global.fetch;const oldEnv={...process.env};Object.assign(process.env,{GEMINI_API_KEY:'test-key',SUPABASE_URL:'https://test.invalid',SUPABASE_SERVICE_KEY:'test-service',VISITOR_SECRET:'test-secret'});
 const calls=[];global.fetch=async(url,opts)=>{calls.push({url,body:opts.body});if(url.includes('baari_claim'))return new Response(JSON.stringify('00000000-0000-0000-0000-000000000001'));if(url.includes('googleapis'))return new Response(JSON.stringify({candidates:[{content:{parts:[{text:'Token 12: estimated wait 16–24 minutes. This may change.'}]},finishReason:'STOP'}],usageMetadata:{promptTokenCount:100,candidatesTokenCount:20}}));if(url.includes('baari_usage'))return new Response(JSON.stringify({messagesGenerated:1,languages:1}));return new Response(null,{status:204});};
 try{const res=response();await handler({method:'POST',headers:{host:'demo.test'},body:sample},res);assert.equal(res.code,200);assert.equal(res.data.stats.messagesGenerated,1);assert.equal(calls.length,4);const saved=JSON.parse(calls[2].body);assert.equal(saved.input_tokens,100);assert.equal(saved.output_tokens,20);assert.equal(saved.status,'complete');const request=JSON.parse(calls[1].body);assert.equal(request.generationConfig.maxOutputTokens,200);}
 finally{global.fetch=oldFetch;for(const k of ['GEMINI_API_KEY','SUPABASE_URL','SUPABASE_SERVICE_KEY','VISITOR_SECRET'])if(oldEnv[k]===undefined)delete process.env[k];else process.env[k]=oldEnv[k];}
});
test('request cap stops a Gemini call',async()=>{const oldFetch=global.fetch;Object.assign(process.env,{GEMINI_API_KEY:'test-key',SUPABASE_URL:'https://test.invalid',SUPABASE_SERVICE_KEY:'test-service',VISITOR_SECRET:'test-secret'});let calls=0;global.fetch=async()=>{calls++;return new Response('null');};try{const res=response();await handler({method:'POST',headers:{host:'demo.test'},body:sample},res);assert.equal(res.code,429);assert.equal(calls,1);}finally{global.fetch=oldFetch;for(const k of ['GEMINI_API_KEY','SUPABASE_URL','SUPABASE_SERVICE_KEY','VISITOR_SECRET'])delete process.env[k];}});
